apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5050"
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
  type: NodePort
